name: Neuen Branch an Jira melden

on:
  workflow_call:
    secrets:
      JIRA_API_TOKEN:
        required: true

jobs:
  comment_in_jira:
    runs-on: ubuntu-latest

    steps:
    
    - name: Bestimme aktuellen Branch
      id: branch-name
      uses: tj-actions/branch-names@v5.1

    - name: Aktuellen Branch in Umgebungsvariable
      run: |
        echo CURRENT_BRANCH=${{ steps.branch-name.outputs.current_branch }} >> $GITHUB_ENV
        
    - name: Jira-Ticket bestimmen
      run: |
        echo JIRA_TICKET=$( echo $CURRENT_BRANCH | perl -lne '@x=split /\-/; print "$x[0]-$x[1]"') >> $GITHUB_ENV
      
    - name: Ticket-Informationen laden
      run: |
          echo JIRA_SUMMARY=$(curl -u "brief@fabianmeier.de:${{ secrets.JIRA_API_TOKEN }}" https://internetfriseur.atlassian.net/rest/api/3/issue/$JIRA_TICKET| jq '.fields.summary') >> $GITHUB_ENV
    
    - name: Überprüfen der Ticket-Informationen
      if: env.JIRA_SUMMARY == null
      run: |
        echo "$CURRENT_BRANCH beginnt nicht mit einem gültigen Jira-Ticket"
        exit 1
    
    - name: Schreiben eines Kommentars
      run : |
        curl --request POST \
            --url "https://internetfriseur.atlassian.net/rest/api/3/issue/$JIRA_TICKET/comment" \
            --user "brief@fabianmeier.de:${{ secrets.JIRA_API_TOKEN }}" \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{
            "body": {
              "type": "doc",
              "version": 1,
              "content": [
                {
                  "type": "paragraph",
                  "content": [
                    {
                      "text": "'"Der Branch $CURRENT_BRANCH wurde erzeugt."'",
                      "type": "text"
                    }
                  ]
                }
              ]
            }
          }'
          
