# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      jira-ticket:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Key eines Jira-Tickets'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
      buildall:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Ob jeder Commit gebaut werden soll'
        # Default value if no value is explicitly provided
        type: boolean
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Talk to Jira
      run: |
          echo JIRA_RESULT=$(curl -u "brief@fabianmeier.de:${{ secrets.JIRA_API_TOKEN }}" https://internetfriseur.atlassian.net/rest/api/3/issue/${{ github.event.inputs.jira-ticket }}| jq '.fields.summary') >> $GITHUB_ENV
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
